### PR TITLE
fix for code sample content type and typo error, fix for api referenc…

### PR DESCRIPTION
**Pull request by khound**
…e status link

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by johnleetran — APPROVED** [review]

**Comment by noahhoffman** [comment]
@khound I wanted to pull down your docs PR and build.  I'm getting errors just running "npm run dev" and don't want to get too distracted.  One thing I noticed when you were demoing in the code-samples page was that some examples have the url at the top and some don't.  Small thing but I think it's good to be consistent and we should follow Example 3 below...

// EXAMPLE 1 
```
curl - H "Authorization: Bearer $token" \
- H "x-api-key: $api_key" \
- X POST \
https: //image.adobe.io/pie/psdService/smartObject \
- d '{
  "inputs": [
<more>....
```

// EXAMPLE 3
```
curl -X POST \
  https://image.adobe.io/pie/psdService/documentOperations \
  -H "Authorization: Bearer $token"  \
  -H "x-api-key: $apiKey" \
  -d '{
  <MORE>....
```

**Comment by noahhoffman** [comment]
@khound Example 4 on sample-code is missing quotes around some of the key names, "storage" and "href":

```
    "fonts": {
        storage: "external",
        href: "<SIGNED_GET_URL_TO_VeganStylePersonalUse.ttf>"
    },
```

**Comment by noahhoffman** [comment]
@khound Example 8 headers are inconsistent

```
  -H 'Authorization: Bearer <auth_token>' \
  -H 'Content-Type: application/json' \
  -H 'x-api-key: <YOUR_API_KEY>' \
```

Should be the following for consistency:

```
  -H "Authorization: Bearer $token"  \
  -H "x-api-key: $apiKey" \
  -H "Content-Type: application/json" \
```

**Comment by noahhoffman** [comment]
@khound Example 13 has trailing comma's that need to removed for both occurrences of

`"orientation": "horizontal",`

**Comment by noahhoffman** [comment]
@khound Example 15, 16 and 17 need formatting.  Something is off, they're the only examples without color, maybe we don't need the two exports at the top of each example.  In fact, maybe we need an Example 0 at the top of the page for "example pre-reqs" that state the user must get an api_key and auth token before trying any of these examples, with links to the docs on these steps?

**Comment by noahhoffman** [comment]
@khound Lightroom examples are inconsistent with the other samples - for example the endpoint is at the bottom of the curl command.

**Comment by khound** [comment]
@noahhoffman Thanks for detailed review. I am checking in the changes with all your feedback implemented and also some more changes to keep the examples consistent

**Pull request merged**
